riak_core_pb.erl:47: Guard test is_list(Records::tuple()) can never succeed
riak_core_pb.erl:70: The pattern <_, 'optional', 'undefined', _, _> can never match the type <1 | 2 | 3,'required',_,'bytes',[]>
riak_core_pb.erl:72: The pattern <_, 'repeated', 'undefined', _, _> can never match the type <1 | 2 | 3,'required',_,'bytes',[]>
riak_core_pb.erl:74: The pattern <_, 'repeated_packed', 'undefined', _, _> can never match the type <1 | 2 | 3,'required',_,'bytes',[]>
riak_core_pb.erl:75: The pattern <_, 'repeated_packed', [], _, _> can never match the type <1 | 2 | 3,'required',_,'bytes',[]>
riak_core_pb.erl:80: The pattern <_, 'repeated', [], _, Acc> can never match the type <1 | 2 | 3,'required',_,'bytes',[]>
riak_core_pb.erl:83: The pattern <FNum, 'repeated', [Head | Tail], Type, Acc> can never match the type <1 | 2 | 3,'required',_,'bytes',[]>
riak_core_pb.erl:86: The pattern <FNum, 'repeated_packed', Data, Type, _> can never match the type <1 | 2 | 3,'required',_,'bytes',[]>
riak_core_pb.erl:101: The call riak_core_pb:enum_to_int(Type::'bytes',Data::atom()) will never return since it differs in the 1st argument from the success typing arguments: ('pikachu','value')
riak_core_pb.erl:148: The pattern 'true' can never match the type 'false'
riak_core_pb.erl:154: The pattern 'true' can never match the type 'false'
riak_core_pb.erl:163: The pattern 'true' can never match the type 'false'
riak_core_pb.erl:175: The pattern {_, _, Dict} can never match the type 'false'
riak_core_pb.erl:193: The pattern 'true' can never match the type 'false'
riak_core_pb.erl:202: The pattern <Binary, 'string'> can never match the type <_,'bytes'>
riak_core_pb.erl:222: The pattern <Types, [{FNum, Bytes} | Tail], Acc> can never match the type <_,[],[{_,_}]>
riak_kv_bitcask_backend.erl:24: Callback info about the riak_kv_backend behaviour is not available
riak_kv_buckets_fsm.erl:27: Callback info about the riak_core_coverage_fsm behaviour is not available
riak_kv_console.erl:154: The pattern {'error', 'legacy_mode'} can never match the type {'error','is_up' | 'not_member' | 'only_member'}
riak_kv_eleveldb_backend.erl:24: Callback info about the riak_kv_backend behaviour is not available
riak_kv_gcounter.erl:64: Invalid type specification for function riak_kv_gcounter:new/2. The success typing is (_,pos_integer()) -> {'ok',riak_kv_gcounter:gcounter()}
riak_kv_gcounter.erl:75: Invalid type specification for function riak_kv_gcounter:update/3. The success typing is ('increment' | {'increment',pos_integer()},_,riak_kv_gcounter:gcounter()) -> {'ok',riak_kv_gcounter:gcounter()}
riak_kv_gcounter.erl:85: Function merge/2 has no local return
riak_kv_gcounter.erl:86: The call riak_kv_gcounter:merge(GCnt1::any(),GCnt2::any(),[]) does not have an opaque term of type riak_kv_gcounter:gcounter() as 3rd argument
riak_kv_gcounter.erl:99: The call riak_kv_gcounter:merge(Rest::any(),RestOfClock2::[tuple()],[{_,_},...]) does not have opaque terms as 2nd and 3rd arguments
riak_kv_gcounter.erl:101: The call riak_kv_gcounter:merge(Rest::any(),Clock2::[tuple()],[{_,_},...]) does not have opaque terms as 2nd and 3rd arguments
riak_kv_index_fsm.erl:38: Callback info about the riak_core_coverage_fsm behaviour is not available
riak_kv_keys_fsm.erl:38: Callback info about the riak_core_coverage_fsm behaviour is not available
riak_kv_memory_backend.erl:40: Callback info about the riak_kv_backend behaviour is not available
riak_kv_multi_backend.erl:24: Callback info about the riak_kv_backend behaviour is not available
riak_kv_multi_prefix_backend.erl:74: Callback info about the riak_kv_backend behaviour is not available
riak_kv_pipe_index.erl:164: Function queue_existing_pipe/4 has no local return
riak_kv_pipe_listkeys.erl:159: Function queue_existing_pipe/3 has no local return
riak_kv_pncounter.erl:100: Function merge/2 has no local return
riak_kv_put_fsm.erl:233: Function init/1 has no local return
riak_kv_put_fsm.erl:238: Record construction #state{robj::riak_object:riak_object(),options::[any()],bkey::{binary() | {binary(),binary()},binary()},vnode_options::[],precommit::[],postcommit::[],timing::[{atom(),{non_neg_integer(),non_neg_integer(),non_neg_integer()}},...],trace::'undefined' | {'ok',_},tracked_bucket::'false',bad_coordinators::[]} violates the declared type of field trace::boolean()
riak_kv_put_fsm.erl:270: The created fun has no local return
riak_kv_put_fsm.erl:825: The pattern <[COP = {'counter_op', _Amt} | T], Acc> can never match the type <[{'details' | 'dw' | 'n_val' | 'pw' | 'retry_put_coordinator_failure' | 'returnbody' | 'sloppy_quorum' | 'timeout' | 'update_last_modified' | 'w','false' | 'infinity' | 'true' | [any()] | non_neg_integer()},...],[{'details' | 'dw' | 'n_val' | 'pw' | 'retry_put_coordinator_failure' | 'returnbody' | 'sloppy_quorum' | 'timeout' | 'update_last_modified' | 'w','false' | 'infinity' | 'true' | [any()] | non_neg_integer()}]>
riak_kv_put_fsm.erl:828: The pattern <[COP = {'crdt_op', _Op} | T], Acc> can never match the type <[{'details' | 'dw' | 'n_val' | 'pw' | 'retry_put_coordinator_failure' | 'returnbody' | 'sloppy_quorum' | 'timeout' | 'update_last_modified' | 'w','false' | 'infinity' | 'true' | [any()] | non_neg_integer()},...],[{'details' | 'dw' | 'n_val' | 'pw' | 'retry_put_coordinator_failure' | 'returnbody' | 'sloppy_quorum' | 'timeout' | 'update_last_modified' | 'w','false' | 'infinity' | 'true' | [any()] | non_neg_integer()}]>
riak_kv_util.erl:283: The pattern 'error' can never match the type 'ok' | 'undefined'
riak_kv_vnode.erl:839: The pattern Q = {'riak_kv_index_v3', _, _, _, _, _, _, _, _, RE, _} can never match the type 'undefined' | {_,_}
riak_kv_vnode.erl:849: The pattern <{'riak_kv_index_v3', _, _, _, _, _, _, _, _, _, N}, DefaultSize> can never match the type <'undefined' | {_,_},'undefined' | pos_integer()>
riak_kv_vnode.erl:970: Invalid type specification for function riak_kv_vnode:prepare_index_query/1. The success typing is ('undefined' | {_,_}) -> 'undefined' | {_,_}
riak_kv_vnode.erl:1002: The call riak_kv_vnode:prepare_index_query(Query::'undefined' | {_,_}) breaks the contract (#riak_kv_index_v3{}) -> #riak_kv_index_v3{}
riak_kv_vnode.erl:1270: Function do_backend_delete/3 has no local return
riak_kv_vnode.erl:1977: Function delete_from_hashtree/3 has no local return
riak_kv_vnode.erl:1981: The call riak_kv_index_hashtree:async_delete(Items::[{'object',{_,_}},...],Trees::'undefined' | pid()) breaks the contract ({binary(),binary()} | [{binary(),binary()}],pid()) -> 'ok'
riak_kv_vnode.erl:1984: The call riak_kv_index_hashtree:delete(Items::[{'object',{_,_}},...],Trees::'undefined' | pid()) breaks the contract ([{binary(),binary()}],pid()) -> 'ok'
riak_kv_vnode.erl:2127: Function update_index_delete_stats/1 will never be called
riak_kv_worker.erl:25: Callback info about the riak_core_vnode_worker behaviour is not available
riak_kv_yessir_backend.erl:109: Callback info about the riak_kv_backend behaviour is not available
Unknown functions:
  cluster_info:dump_all_connected/1
  cluster_info:dump_nodes/2
  cluster_info:format/3
  cluster_info:register_app/1
  dtrace:init/0
  yz_kv:index/3
  yz_kv:is_search_enabled_for_bucket/1
  yz_kv:should_handoff/1
  yz_kv:index_binary/5
Unknown types:
  base64:ascii_binary/0
  calendar:t_now/0
  mochijson2:json_object/0
  mochijson2:json_string/0
  mochijson2:json_term/0
  mochijson2:json_value/0
  proplist:proplist/0
  riak_core_apl:preflist2/0
  riak_dt:operation/0
  riak_dt:value/0
